### ISSUE TITLE
Ordering property is not supported for mobile filter modules

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#447] opened 2018-02-16 09:33 UTC
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'ordering' of bean class [org.jspresso.framework.application.model.mobile.MobileFilterableBeanCollectionModule]

**Comment by vvandens** [comment] 2018-02-16 17:29
Duplicate of #385

**Closed by vvandens** 2018-02-16 17:29 UTC
Labels: 6.0.0, bug, duplicate
