### ISSUE TITLE
Dynamic 'background' and 'description' not working for propertyView

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#646] opened 2018-12-31 13:24 UTC
Here is an example where 'background' and 'description' are ignored :

```
               repeater(model: 'ModificationEvent-deltaList', borderType: 'SIMPLE', preferredWidth:200) {
                    repeat {

                        grid(model: 'Delta') {
                            cells {
                                cell(row:0, column:0, /*width:100, */fillWidth: true) {
                                    propertyView name: 'propertyTranslated', i18nNameKey: 'tracker.property', readOnly: true, width:100, preferredWidth:100, horizontalAlignment: 'RIGHT', foreground: '0xFF777777', font: ';BOLD;'
                                }
                                cell(row:0, column:1) {
                                    propertyView name: 'afterTranslated', i18nNameKey: 'tracker.value', description: 'before', font: ';BOLD;', background: 'afterBackground', booleanWritabilityGates: ['!property']
                                }
                            }
                        }
                    }
                }
```

It is working well using a simple form... but the UI is not perfect (too much spaces between repeated views) :

```
                repeater(model: 'ModificationEvent-deltaList', borderType: 'SIMPLE', preferredWidth:200) {
                    repeat {
                        form(labelsPosition: 'NONE', columnCount: 2, preferredHeight:30, preferredWidth: 200) {
                            fields {
                                propertyView name: 'propertyTranslated', i18nNameKey: 'tracker.property', readOnly: true, horizontalAlignment: 'RIGHT', preferredWidth:150, foreground: '0xFF777777', font: ';BOLD;'
                                propertyView name: 'afterTranslated', i18nNameKey: 'tracker.value', description: 'before', font: ';BOLD;', background: 'afterBackground', booleanWritabilityGates: ['!property']
                            }
                        }
                    }
                }
```

Here is the model :

```
    Component ('Delta', extension:'DeltaExtension') {

        string 'property'
        string_1024 'before', truncate: true
        string_1024 'after', truncate: true

        string_1024 'reference'

        string_1024 'propertyTranslated', id: 'Delta-propertyTranslated'
        string_1024 'afterTranslated', id:'Delta-afterTranslated', truncate: true
        color 'afterBackground'

        text 'afterTranslatedText', computed:true, truncate: true, maxLength:1024

        string 'updatedBy'
        date_time 'updatedTimestamp'

    }
```

**Comment by vvandens** [comment] 2019-01-02 10:41
Duplicate of #645

**Closed** 2019-01-02 10:41 UTC
Labels: 6.0.0, bug, duplicate

**Comment by reshma23** [comment] 2020-07-31 15:30
I am facing an issue in propertyview in filter module.
Issue:
I have migrated the application to HTML supported one.In one of the screen I have datetime field which is created timestamp of jspresso itself.This is mapped as a datepicker field for calendar and textfield for time.The calendar functionality is working but the textfield is showing for time values ie sec , minutes etc.This textfield is partially shown.
Experiments done by increasing the column count and mentioned width .I could see the difference in alignment only not able to chage the width of .My screen have 5fields and two timestamp fields.
Could you please help me on this.
