### ISSUE TITLE
Action view rendering issue when focusing

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#577] opened 2018-07-04 09:47 UTC
The border should be closer to the action :
![image](https://user-images.githubusercontent.com/4968224/42269968-fa49489e-7f7f-11e8-8763-c7eaf2c044f6.png)

**Comment by vvandens** [comment] 2018-10-08 15:29
Duplicate of #605

**Closed by vvandens** 2018-10-08 15:29 UTC
Labels: 6.0.0, duplicate, enhancement
