### ISSUE TITLE
Possible NPE with DefaultCriteriaFactory while using comparableQueryStructures

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#33] opened 2015-07-24 09:58 UTC
Within DefaultCriteriaFactory
method:  protected Criterion createComparableQueryStructureRestriction
Isn't null safe regarding the queryStructure's comparator.

The switch(comparator) may lead to a NPE

    java.lang.NullPointerException
                at org.jspresso.framework.model.persistence.hibernate.criterion.DefaultCriteriaFactory.createComparableQueryStructureRestriction(DefaultCriteriaFactory.java:543)
                at org.jspresso.framework.model.persistence.hibernate.criterion.DefaultCriteriaFactory.completeCriteria(DefaultCriteriaFactory.java:188)
                at org.jspresso.framework.model.persistence.hibernate.criterion.DefaultCriteriaFactory.completeCriteria(DefaultCriteriaFactory.java:243)
                at org.jspresso.framework.model.persistence.hibernate.criterion.DefaultCriteriaFactory.createCriteria(DefaultCriteriaFactory.java:175)
                at org.jspresso.framework.application.backend.action.persistence.hibernate.QueryEntitiesAction.performQuery(QueryEntitiesAction.java:150)
                at org.jspresso.framework.application.backend.action.AbstractQueryComponentsAction.doQuery(AbstractQueryComponentsAction.java:129)
                at org.jspresso.framework.application.backend.action.AbstractQueryComponentsAction.access$000(AbstractQueryComponentsAction.java:60)
                at org.jspresso.framework.application.backend.action.AbstractQueryComponentsAction$1.doInTransaction(AbstractQueryComponentsAction.java:93)
                at org.jspresso.framework.application.backend.action.AbstractQueryComponentsAction$1.doInTransaction(AbstractQueryComponentsAction.java:89)
                at org.jspresso.framework.application.backend.ControllerAwareTransactionTemplate$1.doInTransaction(ControllerAwareTransactionTemplate.java:86)
                at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:131)
                at org.jspresso.framework.application.backend.ControllerAwareTransactionTemplate.execute(ControllerAwareTransactionTemplate.java:89)
                at org.jspresso.framework.application.backend.action.AbstractQueryComponentsAction.execute(AbstractQueryComponentsAction.java:89)
                at org.jspresso.framework.application.backend.AbstractBackendController.execute(AbstractBackendController.java:355)
                at org.jspresso.framework.application.backend.action.AbstractQbeAction.execute(AbstractQbeAction.java:90)
                at org.jspresso.framework.application.backend.AbstractBackendController.execute(AbstractBackendController.java:355)
                at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeBackend(AbstractFrontendController.java:1542)
                at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:582)
                at org.jspresso.framework.application.action.AbstractAction.execute(AbstractAction.java:114)
                at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.executeFrontend(AbstractFrontendController.java:1555)
                at org.jspresso.framework.application.frontend.controller.AbstractFrontendController.execute(AbstractFrontendController.java:584)
                at org.jspresso.framework.view.remote.RemoteActionFactory$ActionAdapter.actionPerformed(RemoteActionFactory.java:235)
                at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommand(AbstractRemoteController.java:437)
                at org.jspresso.framework.application.frontend.controller.remote.AbstractRemoteController.handleCommands(AbstractRemoteController.java:202)
                at org.jspresso.framework.application.startup.remote.RemoteStartup.handleCommands(RemoteStartup.java:88)
                at sun.reflect.GeneratedMethodAccessor1360.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at flex.messaging.services.remoting.adapters.JavaAdapter.invoke(JavaAdapter.java:418)
                at flex.messaging.services.RemotingService.serviceMessage(RemotingService.java:183)
                at flex.messaging.MessageBroker.routeMessageToService(MessageBroker.java:1400)
                at flex.messaging.endpoints.AbstractEndpoint.serviceMessage(AbstractEndpoint.java:1005)
                at flex.messaging.endpoints.amf.MessageBrokerFilter.invoke(MessageBrokerFilter.java:103)
                at flex.messaging.endpoints.amf.LegacyFilter.invoke(LegacyFilter.java:158)
                at flex.messaging.endpoints.amf.SessionFilter.invoke(SessionFilter.java:44)
                at flex.messaging.endpoints.amf.BatchProcessFilter.invoke(BatchProcessFilter.java:67)
                at flex.messaging.endpoints.amf.SerializationFilter.invoke(SerializationFilter.java:166)
                at flex.messaging.endpoints.BaseHTTPEndpoint.service(BaseHTTPEndpoint.java:291)
                at flex.messaging.MessageBrokerServlet.service(MessageBrokerServlet.java:353)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.jspresso.framework.util.http.HttpRequestHolder.doFilter(HttpRequestHolder.java:99)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
                at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:183)
                at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95)
                at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
                at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
                at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
                at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
                at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
                at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:419)
                at org.apache.coyote.ajp.AjpAprProtocol$AjpConnectionHandler.process(AjpAprProtocol.java:425)
                at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:2036)
                at java.lang.Thread.run(Thread.java:724)

**Comment by vvandens** [comment] 2015-09-11 08:34
closed as duplicate of #7

**Closed by vvandens** 2015-09-11 08:34 UTC
Labels: 4.1, bug, duplicate
