### ISSUE TITLE
Overriding view descriptor's tooltip mechanism  

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#96] opened 2016-02-04 09:05 UTC
I would like to be able to override the tooltip visible in the Jspresso UI 
The target is to be able to display "technical" stuff depending of the user's roles.

The icing on the cake would be to be able to clic on some tooltip's hyperlink to raise Jspresso actions !
Or at least I would like to be able to give the focus to the tooltip to be able to select piece of text to copy it to clipboard...

Please help !

**Comment by vvandens** [comment] 2018-02-07 14:08
Duplicate of #377

**Closed by vvandens** 2018-02-07 14:08 UTC
Labels: 6.0.0, duplicate, enhancement
