### ISSUE TITLE
Open the various comparable properties (number, date, time and duration) for an extra customization

### ISSUE THREAD

**Issue by W-Alphonse** [jspresso/jspresso-ce#19] opened 2015-05-07 08:59 UTC
Open the various comparable properties (number, date, time and duration) for an extra customization in order to tell Jspresso whether to generate or not the comparator structure when those properties are added in a filter view.

Something like :
  date 'validityDate', filterComparable:true
   integer 'vehId',  filterComparable:false

**Comment by vvandens** [comment] 2015-05-07 09:10
Isn't this a duplicate of #12 ? It should be already fixed and deployed on 4.1-SNAPSHOT

**Comment by W-Alphonse** [comment] 2015-05-07 09:26
Actually yes, it is a duplication of #12.
Thnak you.

**Closed** 2015-05-07 09:32 UTC
Labels: 4.1, duplicate, enhancement
