### ISSUE TITLE
Action view rendering issue when focusing into it

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#576] opened 2018-07-04 09:39 UTC
The border should be closer to the action button

![image](https://user-images.githubusercontent.com/4968224/42269612-e3f8db28-7f7e-11e8-9f81-9410516b3fad.png)

**Comment by vvandens** [comment] 2018-07-09 11:58
duplicate of #577

**Closed by vvandens** 2018-07-09 11:58 UTC
Labels: 6.0.0, duplicate
