### ISSUE TITLE
LOV property view background is drooling over form's background

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#196] opened 2016-10-14 07:05 UTC
Here is an example 

<img width="1027" alt="capture d ecran 2016-10-12 a 20 12 38" src="https://cloud.githubusercontent.com/assets/4968224/19322260/96dd8f16-90b8-11e6-991e-7604be92b772.png">

**Comment by vvandens** [comment] 2016-10-14 08:12
Duplicate Of #194

**Closed by vvandens** 2016-10-14 08:12 UTC
Labels: 4.2.9, 4.3, bug, duplicate
